spring:
  profiles:
    active: local
  #thymeleaf \uC124\uC815
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/   # .html \uD30C\uC77C \uACBD\uB85C (src/main/resources/templates)
    suffix: .html   # \uD655\uC7A5\uC790
    cache: false # default: true, \uAC1C\uBC1C \uC2DC\uC5D0\uB294 false\uB85C \uB450\uB294 \uAC83\uC774 \uC88B\uC74C
  mvc:
    static-path-pattern: /static/** # spring mvc \uC815\uC801 \uD30C\uC77C\uB4E4\uC758 \uACBD\uB85C (css, js\uD30C\uC77C \uB4F1)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:4306/spring_db # spring_db \uBD80\uBD84\uC740 \uC124\uC815\uD55C DB\uBA85\uACFC \uB9DE\uCD98\uB2E4.
    username: spring
    password: spring-pw # \uBE44\uBC00 \uBC88\uD638\uAC00 \uC788\uC744 \uACBD\uC6B0 \uC124\uC815\uD55C\uB2E4.
mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true # (DB)value_name -> (Java)valueName \uC790\uB3D9 \uB9E4\uD551
server:
  servlet:
    context-path: /
  port: 8080 # \uC6F9 \uC11C\uBC84\uC758 \uD3EC\uD2B8 \uBC88\uD638